# Generated by Django 5.2.6 on 2025-09-23 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudregistropropietario',
            name='vivienda_validada',
            field=models.ForeignKey(blank=True, help_text='Vivienda encontrada en el sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vivienda'),
        ),
        migrations.AddField(
            model_name='relacionespropietarioinquilino',
            name='vivienda',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_propietario_inquilino', to='core.vivienda'),
        ),
        migrations.AlterField(
            model_name='relacionespropietarioinquilino',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_propietario_inquilino', to='core.vivienda'),
        ),
    ]