# Generated by Django 5.2.6 on 2025-09-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_agregar_campos_vivienda'),
        ('authz', '0002_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
    ]
