# Generated by Django 5.2.6 on 2025-09-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authz', '0003_merge_20250923_1645'),
        ('core', '0002_alter_pagos_procesado_por_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='relacionespropietarioinquilino',
            name='unique_active_propietario_inquilino',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='relacionespropietarioinquilino',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('propietario', 'inquilino', 'vivienda'), name='unique_active_propietario_inquilino_vivienda'),
        ),
    ]
