# Generated by Django 5.2.6 on 2025-09-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0004_remove_relacionespropietarioinquilino_unique_active_propietario_inquilino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudregistropropietario',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudregistropropietario',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Motivo del rechazo'),
        ),
        migrations.AddField(
            model_name='solicitudregistropropietario',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones de aprobación'),
        ),
        migrations.AddField(
            model_name='solicitudregistropropietario',
            name='token_seguimiento',
            field=models.CharField(blank=True, help_text='Token único para seguimiento de la solicitud', max_length=50, unique=True),
        ),
    ]
