# Generated by Django 5.2.6 on 2025-09-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0005_crear_solicitud_registro_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudregistropropietario',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Fecha de aprobación de la solicitud', null=True),
        ),
    ]
