# Generated by Django 5.2.6 on 2025-09-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0006_add_fecha_aprobacion_to_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudregistropropietario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto del solicitante para reconocimiento/acceso', null=True, upload_to='solicitudes_fotos/'),
        ),
    ]
