# Generated by Django 5.2.6 on 2025-09-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0007_solicitudregistropropietario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='encoding_facial',
            field=models.JSONField(blank=True, help_text='Lista de codificaciones faciales para reconocimiento (puede ser una lista de listas)', null=True),
        ),
    ]
