# Generated by Django 5.2.6 on 2025-09-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0008_alter_persona_encoding_facial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudregistropropietario',
            name='fotos_reconocimiento_urls',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs de fotos para reconocimiento facial (Dropbox)'),
        ),
    ]
