# Generated by Django 5.2.6 on 2025-09-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0009_solicitudregistropropietario_fotos_reconocimiento_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto_perfil',
            field=models.CharField(blank=True, help_text='URL pública de la foto de perfil (Dropbox)', max_length=512, null=True),
        ),
    ]
