# Generated by Django 5.2.6 on 2025-10-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0010_alter_persona_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='reconocimiento_facial_activo',
            field=models.BooleanField(default=False, help_text='Indica si el reconocimiento facial está activado para esta persona'),
        ),
    ]
