# Generated by Django 5.2.6 on 2025-09-23 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='procesado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_procesados_core', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visita',
            name='guardia_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_atendidas_core', to=settings.AUTH_USER_MODEL),
        ),
    ]
