# Generated by Django 5.2.6 on 2025-09-24 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0005_crear_solicitud_registro_propietario'),
        ('core', '0002_alter_pagos_procesado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='persona_autorizante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authz.persona'),
        ),
        migrations.AlterField(
            model_name='reconocimientofacial',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authz.persona'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authz.persona'),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authz.persona'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authz.persona'),
        ),
        migrations.AlterField(
            model_name='relacionespropietarioinquilino',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='propietarios', to='authz.persona'),
        ),
        migrations.AlterField(
            model_name='avisospersonalizados',
            name='persona_destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authz.persona'),
        ),
        migrations.AlterField(
            model_name='familiarresidente',
            name='familiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='authz.persona'),
        ),
        migrations.AlterField(
            model_name='relacionespropietarioinquilino',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquilinos', to='authz.persona'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authz.persona'),
        ),
        migrations.AlterField(
            model_name='multassanciones',
            name='persona_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authz.persona'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authz.persona'),
        ),
        migrations.AlterField(
            model_name='familiarresidente',
            name='persona_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares_principales', to='authz.persona'),
        ),
        migrations.AlterField(
            model_name='multassanciones',
            name='persona_infractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='infractores', to='authz.persona'),
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
