# Generated by Django 5.2.6 on 2025-09-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_visita_persona_autorizante_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relacionespropietarioinquilino',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='relacionespropietarioinquilino',
            name='inquilino',
        ),
        migrations.RemoveField(
            model_name='relacionespropietarioinquilino',
            name='propietario',
        ),
        migrations.DeleteModel(
            name='FamiliarResidente',
        ),
        migrations.DeleteModel(
            name='RelacionesPropietarioInquilino',
        ),
    ]
