# Generated by Django 5.2.6 on 2025-09-24 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_relacionespropietarioinquilino_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadEspacioComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('capacidad_maxima', models.IntegerField(default=10)),
                ('bloqueado_por_mantenimiento', models.BooleanField(default=False)),
                ('motivo_bloqueo', models.CharField(blank=True, max_length=255, null=True)),
                ('es_recurrente', models.BooleanField(default=False)),
                ('dias_recurrentes', models.JSONField(default=list)),
                ('espacio_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='core.espaciocomun')),
            ],
            options={
                'unique_together': {('espacio_comun', 'fecha_inicio', 'fecha_fin')},
            },
        ),
    ]
