# Generated by Django 5.2.6 on 2025-09-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_disponibilidadespaciocomun'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual')], default=None, max_length=50, null=True),
        ),
    ]
