# Generated by Django 5.2.6 on 2025-09-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_disponibilidadespaciocomun'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='fotos_reconocimiento_urls',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs de fotos para reconocimiento facial'),
        ),
    ]
