# Generated by Django 5.2.6 on 2025-09-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_visita_fotos_reconocimiento_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='fotos_reconocimiento_urls',
        ),
        migrations.AddField(
            model_name='visita',
            name='fotos_reconocimiento',
            field=models.JSONField(blank=True, default=list, help_text='Lista de dicts con path y url de fotos para reconocimiento facial'),
        ),
    ]
