# Generated by Django 5.2.6 on 2025-09-27 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mantenimiento_frecuencia'),
        ('core', '0007_remove_visita_fotos_reconocimiento_urls_and_more'),
    ]

    operations = [
    ]
