# Generated by Django 5.2.6 on 2025-09-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20250926_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensasmensuales',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensas', to='core.vivienda'),
        ),
    ]
