# Generated by Django 5.2.6 on 2025-09-12 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Copropietarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('unidad_residencial', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Copropietario',
                'verbose_name_plural': 'Copropietarios',
                'db_table': 'copropietarios',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='ReconocimientoFacial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor_ia', models.CharField(choices=[('Microsoft', 'Microsoft Azure Face API'), ('Local', 'Reconocimiento Local')], max_length=20)),
                ('vector_facial', models.TextField()),
                ('imagen_referencia_url', models.URLField(blank=True, null=True)),
                ('imagen_referencia_path', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_enrolamiento', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('confianza_enrolamiento', models.FloatField(blank=True, null=True)),
                ('intentos_verificacion', models.PositiveIntegerField(default=0)),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True)),
                ('copropietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimiento_facial', to='seguridad.copropietarios')),
            ],
            options={
                'verbose_name': 'Reconocimiento Facial',
                'verbose_name_plural': 'Reconocimientos Faciales',
                'db_table': 'reconocimiento_facial',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguridad.roles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='BitacoraAcciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_accion', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('ENROLL_FACE', 'Enrolamiento Biométrico'), ('VERIFY_FACE', 'Verificación Biométrica'), ('DELETE_FACE', 'Eliminación Biométrico'), ('ACCESS_GRANTED', 'Acceso Concedido'), ('ACCESS_DENIED', 'Acceso Denegado'), ('SYSTEM_ERROR', 'Error del Sistema')], max_length=20)),
                ('descripcion', models.TextField()),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('proveedor_ia', models.CharField(blank=True, max_length=20, null=True)),
                ('confianza', models.FloatField(blank=True, null=True)),
                ('resultado_match', models.BooleanField(blank=True, null=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('copropietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_bitacora', to='seguridad.copropietarios')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_bitacora', to='seguridad.usuarios')),
            ],
            options={
                'verbose_name': 'Bitácora de Acción',
                'verbose_name_plural': 'Bitácora de Acciones',
                'db_table': 'bitacora_acciones',
                'ordering': ['-fecha_accion'],
            },
        ),
    ]
