# Generated by Django 5.2.6 on 2025-09-23 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='rol',
        ),
        migrations.AddField(
            model_name='copropietarios',
            name='tipo_residente',
            field=models.CharField(choices=[('Propietario', 'Propietario'), ('Inquilino', 'Inquilino'), ('Familiar', 'Familiar'), ('Visitante', 'Visitante Frecuente')], default='Propietario', max_length=20),
        ),
        migrations.AddField(
            model_name='copropietarios',
            name='usuario_sistema',
            field=models.OneToOneField(blank=True, help_text='Usuario del sistema asociado a este copropietario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copropietario_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bitacoraacciones',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_bitacora', to=settings.AUTH_USER_MODEL),
        ),
    ]
