# Generated by Django 5.2.6 on 2025-09-23 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_remove_usuarios_rol_copropietarios_tipo_residente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
