# Generated by Django 5.2.5 on 2025-09-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_add_propietarios_compatibility'),
        ('seguridad', '0003_delete_roles_delete_usuarios'),
    ]

    operations = [
    ]
