# Generated by Django 5.2.6 on 2025-09-24 02:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_pagos_procesado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensasMensuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_year', models.IntegerField()),
                ('periodo_month', models.IntegerField()),
                ('monto_base_administracion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_mantenimiento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_servicios_comunes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_seguridad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_ingresos_expensas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_ingresos_multas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_ingresos_reservas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_ingresos_otros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_egresos_salarios', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_egresos_mantenimiento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_egresos_servicios', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_egresos_mejoras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo_inicial_periodo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo_final_periodo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_reporte_url', models.URLField(blank=True, null=True)),
                ('enviado_personas', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('morosa', 'Morosa')], default='pendiente', max_length=20)),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensas', to='core.vivienda')),
            ],
            options={
                'unique_together': {('vivienda', 'periodo_year', 'periodo_month')},
            },
        ),
    ]
