# Generated by Django 5.2.6 on 2025-09-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensas_multas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpensasMensuales',
        ),
    ]
